language: objective-c
before_install:
    - brew update
    - brew upgrade xctool
script: xctool -project "hashtag-warrior.xcodeproj" -scheme "#Warrior" -configuration "Release" -sdk "iphonesimulator7.0" test
